### ISSUE TITLE
PETSCII -> screen code

### ISSUE THREAD

**Issue by lagomorph** [Jeff-Birt/TASM_vsCode_Extension#1]
Hey Birt! 🙂

Just a pedantic nit in your PDF regarding PETSCII in the C64 example... while Commodores do use PETSCII instead of ASCII, in the example you're actually using screen codes. These are just indices into character ROM (x8).

**Comment by Jeff-Birt** [comment]
Thanks for pointing that out. I just updated the PDF to try and clarify.
